### PR TITLE
Update displayed network types to not be the literal constant values.

### PR DESCRIPTION
**Pull request by TimBarham**
(request from documentation)

Also, include them in the HTML so they're localizable.

### CODE REVIEW

**Comment by TimBarham** [comment]
@MSLaguana - got a moment to review this? Pretty simple change.

**Comment by MSLaguana** [comment]
Looks good once you clean up those unused variables.

**Comment by albertinad** [comment]
LGTM!

**Comment by TimBarham** [comment]
Thanks!

**Pull request merged**
