### PR TITLE
Changing default theme

### PR DESCRIPTION
**Pull request by dlebu**
This PR contains styling changes to the default theme. Here is a screenshot of the new design:

screen shot 2016-05-25 at 8 26 17 am

### CODE REVIEW

**Comment by dlebu** [comment]
@guillaumejenkins @hamiltonia Waiting for at least one sign off. @albertinad is fine with changing the default theme, since the XDK uses a different one.

**Comment by albertinad** [comment]
LGTM.

**Comment by TimBarham** [comment]
Hey @dlebu - I know this is already merged (and looks great) - but just wondering if you could tweak the vertical position of the panel collapse icon - it's too low. Moving it up 2 pixels would center it.

**Comment by dlebu** [comment]
@TimBarham thanks for the feedback. I'll make the change and open a new issue to track it.

**Pull request merged**
