### PR TITLE
Fixed bug with not fired onDeviceReady event

### PR DESCRIPTION
**Pull request by paymicro**
Fixed bug with not fired onDeviceReady event, due to a broken webSocket connection in debug mode.

At the time of debugging, a loss of the WebSocket connection can occur because of this, the onCordovaSimulateReady and onDeviceReady events are not triggered.

### CODE REVIEW

**Comment by TimBarham** [comment]
Is this a fix for #245? If so, it seems the problem there is that the simulation host window never opens. Since the simulation host is what triggers start (once it is initialized), that would be why start never gets fired. So I wonder if the problem really needs to be fixed elsewhere - figuring out why the simulation host window doesn't open.

**Comment by busykai** [comment]
It does seem to me that if `sim-host` never tells `app-host` to start, then it should hang (which it correctly does).

Simply firing `deviceReady` on `reconnect` is not the right thing to do. The bootstrap protocol between `sim-host` and `app-host` should resume on `reconnect`. `app-host` cannot make unilateral decision that it's ready.

**Comment by paymicro** [comment]
@TimBarham this is another bug. It is not due to the fact that in the process of app-host debugging the connection to the server through the sockets is lost.
This fix allows after the reconnect, register on the server and run the onCordovaSimulateReady event.

**Comment by paymicro** [comment]
@busykai In this case, sim-host and app-host are executed correctly. 
A bug may occur if you start debugging app-host between the events onNativeReady and onCordovaSimulateReady.

**Comment by TimBarham** [comment]
Sorry for the delay getting back... my comment still applies - `app-host` should never fire `deviceReady` unless and until it receives `start` from the `sim-host`.

**Comment by paymicro** [comment]
@TimBarham I updated PR. `app-host` not fire `deviceReady`. 
After autoreconnection, he registered on the server. And sends plugin list to `sim-host`, if `deviceReady` not fired.

**Comment by EzioLi01** [comment]
Close this PR since no further updates for 5+ years, please reopen this if you still want to work on this.

**Pull request closed without merging**
