### PR TITLE
Create Travis configuration

### PR DESCRIPTION
**Pull request by busykai**
Adds travis configuration to the repository. This runs the default task (which is linting right now).

A repository owner (admin) should login to https://travis-ci.org with a github accound and enable and configure travis for the repository. Detailed instructions:

1. Click `+` next to my repository.
2. Nagivate to `Microsoft` organization and then locate `cordova-simulate repository`.
3. Enable it (slider to `On`).
4. Click the gear next to `cordova-simulate` to configure details.
5. Turn ON `Build only if .travis.yml is present`.
6. Turn OFF `Build pushes`.
7. Turn OFF `Limit concurrent jobs`.
8. Turn ON `Build pull requests`.

Upon successful configuration, this pull request will have associated CI status.

### CODE REVIEW

**Comment by dlebu** [comment]
@busykai I followed the steps you provided. If everything went well, we should see the build on your next commit, since 

> Travis only runs a build on the commits you push after adding the repository to Travis.

From [here](https://docs.travis-ci.com/user/getting-started/).

**Comment by dlebu** [comment]
https://travis-ci.org/Microsoft/cordova-simulate

**Comment by busykai** [comment]
Yep. It works! :)

**Comment by busykai** [comment]
Merging.

**Pull request merged**
