### PR TITLE
#217. Add exception handler for statSync.

### PR DESCRIPTION
**Pull request by dmitrii-snytkin**

### CODE REVIEW

**Comment by dmitrii-snytkin** [comment]
Fix for bug https://github.com/Microsoft/cordova-simulate/issues/217

**Comment by TimBarham** [comment]
LGTM. Although I probably wouldn't bother with the warning, since the only reason `statSync` should throw is if the file/directory no longer exists, and that isn't really an error/warning situation.

**Comment by TimBarham** [comment]
Actually, another thought I had here: when a watched file is deleted, we don't want to just bail. It should probably trigger a reload, since it is a legitimate change to the app. So I think we should probably not return here. But we will likely need to add special handling for deleted files later on.

**Comment by dmitrii-snytkin** [comment]
I think, that deleting of www directory is not a legitimate change, because it brokes a work of application. And to skip of deleting www directory is better, than to react on this change. Anyway, if www directory appears, `handleWatcherEvent` will called and app will reload correctly.

**Comment by TimBarham** [comment]
But the bug isn't about deleting the `www` folder - it's about deleting a watched file in the `www` folder, which is a legit scenario.

**Comment by dmitrii-snytkin** [comment]
yes, I'm wrong.

**Comment by dmitrii-snytkin** [comment]
Will @TimBarham approve PR?)

**Comment by TimBarham** [comment]
It looks like we still need to handle this later on. As this change currently stands, when a file is deleted, we hit a warning [here](https://github.com/Microsoft/cordova-simulate/blob/statSync-exception-handler/src/server/live-reload/live-reload.js#L83) and nothing else happens. I think instead deleting a file should trigger the following:

* In `live-reload.js`, delete the corresponding file in the platform folder.
* In `src/app-host/live-reload-client.js`, a deleted file should trigger reloading the page.

**Comment by TimBarham** [comment]
Ok, I've made the change so I can merge this and do a release.

**Pull request merged**
